spring:
  data:
    mongodb:
      host: localhost
      database: admin
      username: root
      password: localhost
      morphia:
        basePackage: id.jasoet.extractor.app.model
        dataStoreId: extractor
